
(import (scheme base)
  (texmacs protocol)
  (liii os)
  (liii path)
  (liii uuid)
  (liii sys)
  (liii string)
  (liii list)
)

(define (escape-string str)
  (string-join
    (map (lambda (char)
           (if (char=? char #\")
               (string #\\ #\")
               (if (char=? char #\\)
                   (string #\\ #\\)
                   (string char))))
         (string->list str))))

(define (goldfish-quote s)
  (string-append "\"" (escape-string s) "\""))

(define (tikz-welcome)
  (flush-prompt "tikz] ")
  (flush-verbatim "Liii STEM interface to TikZ"))

(define (tikz-read-code)
  (define (read-code code)
    (let ((line (read-line)))
      (if (or (eof-object? line) (string=? line "<EOF>\n"))
          code
          (read-code (string-append code line)))))
  (read-code ""))

(define (gen-temp-path)
  (let ((tikz-tmpdir (string-append (os-temp-dir) "/tikz")))
    (when (not (file-exists? tikz-tmpdir))
      (mkdir tikz-tmpdir))
    (string-append tikz-tmpdir "/" (uuid4))))

(define (wrap-tikz-code code)
  (let ((trimmed (string-trim-left code)))
    (if (string-starts? trimmed "\\documentclass")
        code
        (let ((inner-code
                (if (or (string-starts? trimmed "\\usetikzlibrary")
                        (string-starts? trimmed "\\begin{tikzpicture}"))
                    code
                    (string-append "\\begin{tikzpicture}\n" code "\n\\end{tikzpicture}"))))
          (string-append
            "\\documentclass[tikz]{standalone}\n\\begin{document}\n"
            inner-code
            "\n\\end{document}")))))

(define (parse-magic-line magic-line)
  (let ((tokens (filter (lambda (x) (not (string-null? x)))
                        (string-split magic-line #\space)))
        (width "0px")
        (height "0px"))
    (let loop ((args (cdr tokens)))
      (cond ((or (null? args) (null? (cdr args)))
             (list width height))
            ((string=? (car args) "-width")
             (set! width (cadr args))
             (loop (cddr args)))
            ((string=? (car args) "-height")
             (set! height (cadr args))
             (loop (cddr args)))
            (else (loop (cddr args))))))))

(define (dump-tex-code code-path code)
  (with-output-to-file code-path
    (lambda () (display code))))

(define (tikz-temp-dir)
  (string-append (os-temp-dir) "/tikz"))

(define (run-pdflatex tex-path pdflatex-bin)
  (display "[tikz-debug] run-pdflatex start: ") (display tex-path) (newline)
  (let* ((inner-cmd (string-append (goldfish-quote pdflatex-bin)
                                   " --interaction=errorstopmode -halt-on-error "
                                   (goldfish-quote tex-path)
                                   " > /dev/null 2>&1"))
         (cmd (string-append "sh -c " (goldfish-quote inner-cmd)))
         (orig-dir (getcwd)))
    (unsetenv "DYLD_LIBRARY_PATH")
    (unsetenv "DYLD_FRAMEWORK_PATH")
    (unsetenv "DYLD_FALLBACK_LIBRARY_PATH")
    (unsetenv "DYLD_FALLBACK_FRAMEWORK_PATH")
    (chdir (tikz-temp-dir))
    (let ((result (os-call cmd)))
      (chdir orig-dir)
      (display "[tikz-debug] run-pdflatex end, result=") (display result) (newline)
      result)))

(define (image-valid? path)
  (display "[tikz-debug] image-valid? ") (display path) (newline)
  (and (file-exists? path) (> (path-getsize path) 10)))

(define (parse-papersize line)
  (display "[tikz-debug] parse-papersize: ") (display line) (newline)
  (let* ((parts (string-split line #\=))
         (size-part (cadr parts))
         (dims (string-split size-part #\,))
         (w-str (string-remove-suffix (car dims) "pt"))
         (h-str (string-remove-suffix (cadr dims) "pt"))
         (w (string->number w-str))
         (h (string->number h-str)))
    (display "[tikz-debug] parsed w=") (display w) (display " h=") (display h) (newline)
    (if (and w h)
        (cons w h)
        (cons 0 0))))

(define (pdf-page-size log-path)
  (display "[tikz-debug] pdf-page-size start: ") (display log-path) (newline)
  (if (not (file-exists? log-path))
      (begin
        (display "[tikz-debug] log file not found") (newline)
        (cons 0 0))
      (let ((p (open-input-file log-path)))
        (display "[tikz-debug] log file opened") (newline)
        (let loop ((n 0))
          (display "[tikz-debug] reading line ") (display n) (newline)
          (if (>= n 100)
              (begin
                (display "[tikz-debug] reached 100 lines, giving up") (newline)
                (close-input-port p)
                (cons 0 0))
              (let ((line (read-line p)))
                (display "[tikz-debug] line read: ")
                (if (eof-object? line)
                    (display "<EOF>")
                    (display line))
                (newline)
                (cond ((eof-object? line)
                       (display "[tikz-debug] EOF reached") (newline)
                       (close-input-port p)
                       (cons 0 0))
                      ((string-contains? line "papersize=")
                       (display "[tikz-debug] found papersize=") (newline)
                       (let ((size (parse-papersize line)))
                         (close-input-port p)
                         (display "[tikz-debug] pdf-page-size returning ") (display size) (newline)
                         size))
                      (else (loop (+ n 1))))))))))

(define (pdf-page-empty? log-path)
  (display "[tikz-debug] pdf-page-empty? start") (newline)
  (let ((size (pdf-page-size log-path)))
    (display "[tikz-debug] pdf-page-empty? got size ") (display size) (newline)
    (let ((w (car size))
          (h (cdr size)))
      (display "[tikz-debug] pdf-page-empty? result ") (display (or (<= w 1.0) (<= h 1.0))) (newline)
      (or (<= w 1.0) (<= h 1.0)))))

(define (flush-image path width height)
  (display "[tikz-debug] flush-image: ") (display path)
  (display " width=") (display width)
  (display " height=") (display height) (newline)
  (if (image-valid? path)
      (flush-file (string-append path "?" "width=" width "&" "height=" height))
      (flush-verbatim "Failed to generate image")))

(define (eval-and-print code width height)
  (display "[tikz-debug] eval-and-print start") (newline)
  (let* ((temp-path (gen-temp-path))
         (tex-path (string-append temp-path ".tex"))
         (pdf-path (string-append temp-path ".pdf"))
         (log-path (string-append temp-path ".log"))
         (wrapped-code (wrap-tikz-code code))
         (pdflatex-bin (fourth (argv))))
    (display "[tikz-debug] temp-path=") (display temp-path) (newline)
    (display "[tikz-debug] pdflatex-bin=") (display pdflatex-bin) (newline)
    (dump-tex-code tex-path wrapped-code)
    (display "[tikz-debug] tex dumped") (newline)
    (if (zero? (run-pdflatex tex-path pdflatex-bin))
        (begin
          (display "[tikz-debug] pdflatex succeeded, checking empty") (newline)
          (if (pdf-page-empty? log-path)
              (begin
                (display "[tikz-debug] page empty, flushing verbatim") (newline)
                (flush-verbatim "TikZ produced an empty image (0x0 bounding box)"))
              (begin
                (display "[tikz-debug] page not empty, computing size") (newline)
                (let ((final-width width)
                      (final-height height))
                  (when (and (string=? width "0px") (string=? height "0px"))
                    (display "[tikz-debug] no size specified, reading from log") (newline)
                    (let* ((size (pdf-page-size log-path))
                           (w-pt (car size))
                           (h-pt (cdr size)))
                      (display "[tikz-debug] got size w-pt=") (display w-pt)
                      (display " h-pt=") (display h-pt) (newline)
                      (when (and (> w-pt 0) (> h-pt 0))
                        (let ((w-px (inexact->exact (round (* w-pt 2))))
                              (h-px (inexact->exact (round (* h-pt 2)))))
                          (display "[tikz-debug] computed px w=") (display w-px)
                          (display " h=") (display h-px) (newline)
                          (set! final-width (string-append (number->string w-px) "px"))
                          (set! final-height (string-append (number->string h-px) "px"))))))
                  (display "[tikz-debug] flushing image") (newline)
                  (flush-image pdf-path final-width final-height)))))
        (begin
          (display "[tikz-debug] pdflatex failed") (newline)
          (flush-verbatim "pdflatex error")
          (flush-verbatim "")))))

(define (split-code-and-magic code)
  (if (not (string-starts? code "%"))
      (list "" code)
      (let ((i/false (string-index code #\newline)))
        (if (not i/false)
            (list code "")
            (list (substring code 0 i/false)
                  (substring code (+ i/false 1)))))))

(define (read-eval-print)
  (let* ((raw-code (tikz-read-code))
         (l (split-code-and-magic raw-code))
         (magic-line (car l))
         (code (cadr l))
         (parsed (if (string-null? magic-line)
                     (list "0px" "0px")
                     (parse-magic-line magic-line)))
         (width (car parsed))
         (height (cadr parsed)))
    (if (string-null? code)
        (flush-verbatim "No code provided!")
        (eval-and-print code width height))))

(define (safe-read-eval-print)
  (catch #t
    (lambda () (read-eval-print))
    (lambda args
      (flush-scheme
        (string-append "(errput (document "
                       (goldfish-quote (symbol->string (car args)))
                       " "
                       (if (and (>= (length args) 2) (not (null? (cadr args))))
                           (goldfish-quote (object->string (cadr args)))
                           "")
                       "))")))))

(define (tikz-repl)
  (safe-read-eval-print)
  (tikz-repl))

(tikz-welcome)
(tikz-repl)
