
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : mathml-drd.scm
;; DESCRIPTION : DRD properties for MathML
;; COPYRIGHT   : (C) 2004  Joris van der Hoeven
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (html mathml-drd))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Ordinary symbols
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(logic-table tm->mathml-constant%
 ("<mathcatalan>" "C")
 ("<mathe>" "e")
 ("<matheuler>" "&eulergamma;")
 ("<mathi>" "&ImaginaryI;")
 ("<mathpi>" "&pi;")
) ;logic-table

(logic-table mathml-constant->tm%
 ("&eulergamma;" "<matheuler>")
 ("&ImaginaryI;" "<mathi>")
 ("&ii;" "<mathi>")
 ("&pi;" "<mathpi>")
 ("&true;" "true")
 ("&false;" "false")
 ("&phiv;" "<varphi>")
 ("&ell;" "<ell>")
 ("&Copf;" "<bbb-C>")
 ("&Qopf;" "<bbb-Q>")
 ("&Zopf;" "<bbb-Z>")
 ("&Ropf;" "<bbb-R>")
) ;logic-table

(logic-table tm->mathml-operator%
 ("&" "&amp;")
 ("<less>" "&lt;")
 ("*" "&InvisibleTimes;")
 (" " "&ApplyFunction;")
) ;logic-table

(logic-table mathml-operator->tm%
 ("⁢" "*")
 ("*" "*")
 ("−" "-")
 ("⃛" "<dddot>")
 ("˚" "<abovering>")
 ("´" "<acute>")
 ("`" "<grave>")
 ("¯" "¯")
 ("‾" "¯")
 ("̲" "¯")
 ("⃗" "<vect>")
 ("̑" "<invbreve>")
 ("ˇ" "<check>")
 ("˘" "<breve>")
 ("⏞" "<overbrace>")
 ("︷" "<overbrace>")
 ("⏟" "<underbrace>")
 ("︸" "<underbrace>")
 ("⎴" "<sqoverbrace>")
 ("﹇" "<sqoverbrace>")
 ("﹈" "<squnderbrace>")
 ("⎵" "<squnderbrace>")
 ("⏜" "<poverbrace>")
 ("︵" "<poverbrace>")
 ("⏝" "<punderbrace>")
 ("︶" "<punderbrace>")
 ("︿" "^")
 ("﹀" "<check>")

 ("&InvisibleTimes;" "*")
 ("&PlusMinus;" "<pm>")
 ("&it;" "*")
 ("&leq;" "<leq>")
 ("&geq;" "<geq>")
 ("&RightArrow;" "<rightarrow>")
 ("&OverBar;" "¯")

 ("&DifferentialD;" "<mathd>")
 ("&Sum;" "<sum>")
 ("&straightphi;" "<phi>")
 ("&PartialD;" "<partial>")
 ("&UnderBrace;" "<underbrace>")
 ("&OverBrace;" "<overbrace>")
 ("&ee;" "<mathe>")
 ("&plus;" "+")
 ("&minus;" "-")
 ("&times;" "<times>")
 ("&divide;" "<div>")
 ("&equals;" "=")
 ("&ne;" "<neq>")
 ("&plusmn;" "<pm>")
 ("&not;" "<neg>")
 ("&gt;" "<gtr>")
 ("&deg;" "<#00B0>")
 ("&bigcup;" (big "cup"))
 ("&bigcap;" (big "cap"))
 ("&Integral;" (big "int"))
 ("&hamilt;" "<#210B>")
 ("&planckh;" "<#210E>")
 ("&planck;" "<hbar>")
 ("&image;" "<#2111>")
 ("&weierp;" "<#2118>")
 ("&real;" "<#211C>")
 ("&mho;" "<#2127>")
 ("&iiota;" "<#2129>")
 ("&bernou;" "<#212C>")
 ("&alefsym;" "<#2135>")
 ("&beth;" "<#2136>")
 ("&gimel;" "<#2137>")
 ("&daleth;" "<#2138>")
 ("&DD;" "<bbb-D>")
 ("&dd;" "<bbb-d>")
 ("&starf;" "<#2605>")
 ("&star;" "<#2606>")
 ("&loz;" "<#25CA>")
 ("&sung;" "<#266A>")
 ("&flat;" "<#266D>")
 ("&natural;" "<#266E>")
 ("&sharp;" "<#266F>")
 ("&check;" "<#2713>")
 ("&cross;" "<#2717>")
 ("&malt;" "<#2720>")
 ("&sext;" "<#2736>")
 ("&VerticalSeparator;" "<#2758>")
 ("&excl;" "<#0021>")
 ("&num;" "<#0023>")
 ("&percnt;" "<#0025>")
 ("&lpar;" "<#0028>")
 ("&rpar;" "<#0029>")
 ("&ast;" "<#002A>")
 ("&comma;" "<#002C>")
 ("&period;" "<#002E>")
 ("&sol;" "<#002F>")
 ("&colon;" "<#003A>")
 ("&semi;" "<#003B>")
 ("&quest;" "<#003F>")
 ("&lbrack;" "<#005B>")
 ("&bsol;" "<#005C>")
 ("&rbrack;" "<#005D>")
 ("&Hat;" "<#005E>")
 ("&lowbar;" "<#005F>")
 ("&grave;" "<#0060>")
 ("&lbrace;" "<#007B>")
 ("&vert;" "<#007C>")
 ("&rbrace;" "<#007D>")
 ("&tilde;" "<#007E>")
 ("&circ;" "<#02C6>")
 ("&nbsp;" "<#00A0>")
 ("&ensp;" "<#2002>")
 ("&emsp;" "<#2003>")
 ("&thinsp;" "<#2009>")
 ("&zwnj;" "<#200C>")
 ("&zwj;" "<#200D>")
 ("&iexcl;" "<#00A1>")
 ("&brvbar;" "<#00A6>")
 ("&sect;" "<#00A7>")
 ("&uml;" "<#00A8>")
 ("&ordf;" "<#00AA>")
 ("&shy;" "<#00AD>")
 ("&macr;" "<#00AF>")
 ("&acute;" "<#00B4>")
 ("&micro;" "<#00B5>")
 ("&para;" "<#00B6>")
 ("&middot;" "<#00B7>")
 ("&cedil;" "<#00B8>")
 ("&ordm;" "<#00BA>")
 ("&iquest;" "<#00BF>")
 ("&hyphen;" "<#2010>")
 ("&ndash;" "<#2013>")
 ("&mdash;" "<#2014>")
 ("&horbar;" "<#2015>")
 ("&Vert;" "<#2016>")
 ("&dagger;" "<#2020>")
 ("&Dagger;" "<#2021>")
 ("&bull;" "<#2022>")
 ("&nldr;" "<#2025>")
 ("&hellip;" "<#2026>")
 ("&permil;" "<#2030>")
 ("&pertenk;" "<#2031>")
 ("&prime;" "<#2032>")
 ("&Prime;" "<#2033>")
 ("&tprime;" "<#2034>")
 ("&bprime;" "<#2035>")
 ("&oline;" "¯")
 ("&caret;" "<#2041>")
 ("&hybull;" "<#2043>")
 ("&frasl;" "/")
 ("&sup1;" "<#00B9>")
 ("&sup2;" "<#00B2>")
 ("&sup3;" "<#00B3>")
 ("&fnof;" "<#0192>")
 ("&percnt;" "<#0025>")
 ("&permil;" "<#2030>")
 ("&pertenk;" "<#2031>")
 ("&forall;" "<#2200>")
 ("&comp;" "<#2201>")
 ("&part;" "<partial>")
 ("&exist;" "<#2203>")
 ("&nexist;" "<#2204>")
 ("&empty;" "<#2205>")
 ("&nabla;" "<#2207>")
 ("&isin;" "<#2208>")
 ("&notin;" "<#2209>")
 ("&ni;" "<#220B>")
 ("&notni;" "<#220C>")
 ("&prod;" (big "prod"))
 ("&coprod;" (big "amalg"))
 ("&sum;" (big "sum"))
 ("&mnplus;" <mp>)
 ("&setminus;" "<#2216>")
 ("&lowast;" "<#2217>")
 ("&compfn;" "<circ>")
 ("&radic;" "<#221A>")
 ("&prop;" "<#221D>")
 ("&infin;" "<#221E>")
 ("&angrt;" "<#221F>")
 ("&ang;" "<#2220>")
 ("&mid;" "<#2223>")
 ("&parallel;" "<#2225>")
 ("&and;" "<#2227>")
 ("&or;" "<#2228>")
 ("&cap;" "<#2229>")
 ("&cup;" "<#222A>")
 ("&int;" "<#222B>")
 ("&Int;" "<#222C>")
 ("&iiint;" "<#222D>")
 ("&conint;" "<#222E>")
 ("&Conint;" "<#222F>")
 ("&Cconint;" "<#2230>")
 ("&there4;" "<#2234>")
 ("&because;" "<#2235>")
 ("&ratio;" "<#2236>")
 ("&Colon;" "<#2237>")
 ("&homtht;" "<#223B>")
 ("&sim;" "<#223C>")
 ("&bsim;" "<#223D>")
 ("&ac;" "<#223E>")
 ("&acd;" "<#223F>")
 ("&sime;" "<#2243>")
 ("&nsime;" "<#2244>")
 ("&cong;" "<#2245>")
 ("&simne;" "<#2246>")
 ("&ncong;" "<#2247>")
 ("&asymp;" "<#2248>")
 ("&nap;" "<#2249>")
 ("&approxeq;" "<#224A>")
 ("&asympeq;" "<#224D>")
 ("&bump;" "<#224E>")
 ("&bumpe;" "<#224F>")
 ("&ecir;" "<#2256>")
 ("&cire;" "<#2257>")
 ("&equiv;" "<#2261>")
 ("&nequiv;" "<#2262>")
 ("&le;" "<#2264>")
 ("&ge;" "<#2265>")
 ("&lE;" "<#2266>")
 ("&gE;" "<#2267>")
 ("&lnE;" "<#2268>")
 ("&gnE;" "<#2269>")
 ("&Lt;" "<#226A>")
 ("&Gt;" "<#226B>")
 ("&NotCupCap;" "<#226D>")
 ("&nlt;" "<#226E>")
 ("&ngt;" "<#226F>")
 ("&nle;" "<#2270>")
 ("&nge;" "<#2271>")
 ("&lsim;" "<#2272>")
 ("&gsim;" "<#2273>")
 ("&nlsim;" "<#2274>")
 ("&ngsim;" "<#2275>")
 ("&pr;" "<#227A>")
 ("&sc;" "<#227B>")
 ("&prcue;" "<#227C>")
 ("&sccue;" "<#227D>")
 ("&prsim;" "<#227E>")
 ("&scsim;" "<#227F>")
 ("&npr;" "<#2280>")
 ("&nsc;" "<#2281>")
 ("&sub;" "<#2282>")
 ("&sup;" "<#2283>")
 ("&nsub;" "<#2284>")
 ("&nsup;" "<#2285>")
 ("&sube;" "<#2286>")
 ("&supe;" "<#2287>")
 ("&nsube;" "<#2288>")
 ("&nsupe;" "<#2289>")
 ("&subne;" "<#228A>")
 ("&supne;" "<#228B>")
 ("&uplus;" "<#228E>")
 ("&sqsub;" "<#228F>")
 ("&sqsup;" "<#2290>")
 ("&sqsube;" "<#2291>")
 ("&sqsupe;" "<#2292>")
 ("&sqcap;" "<#2293>")
 ("&sqcup;" "<#2294>")
 ("&oplus;" "<#2295>")
 ("&ominus;" "<#2296>")
 ("&otimes;" "<#2297>")
 ("&osol;" "<#2298>")
 ("&odot;" "<#2299>")
 ("&ocir;" "<#229A>")
 ("&oast;" "<#229B>")
 ("&odash;" "<#229D>")
 ("&plusb;" "<#229E>")
 ("&minusb;" "<#229F>")
 ("&timesb;" "<#22A0>")
 ("&sdotb;" "<#22A1>")
 ("&vdash;" "<#22A2>")
 ("&dashv;" "<#22A3>")
 ("&top;" "<#22A4>")
 ("&perp;" "<#22A5>")
 ("&models;" "<#22A7>")
 ("&vDash;" "<#22A8>")
 ("&Vdash;" "<#22A9>")
 ("&Vvdash;" "<#22AA>")
 ("&prurel;" "<#22B0>")
 ("&vltri;" "<#22B2>")
 ("&vrtri;" "<#22B3>")
 ("&ltrie;" "<#22B4>")
 ("&rtrie;" "<#22B5>")
 ("&hercon;" "<#22B9>")
 ("&xwedge;" "<#22C0>")
 ("&xvee;" "<#22C1>")
 ("&xcap;" "<#22C2>")
 ("&xcup;" "<#22C3>")
 ("&diamond;" "<#22C4>")
 ("&sdot;" "<#22C5>")
 ("&Star;" "<#22C6>")
 ("&ltimes;" "<#22C9>")
 ("&rtimes;" "<#22CA>")
 ("&lthree;" "<#22CB>")
 ("&rthree;" "<#22CC>")
 ("&bsime;" "<#22CD>")
 ("&cuvee;" "<#22CE>")
 ("&cuwed;" "<#22CF>")
 ("&Sub;" "<#22D0>")
 ("&Sup;" "<#22D1>")
 ("&Cap;" "<#22D2>")
 ("&Cup;" "<#22D3>")
 ("&Ll;" "<#22D8>")
 ("&Gg;" "<#22D9>")
 ("&cuepr;" "<#22DE>")
 ("&cuesc;" "<#22DF>")
 ("&nprcue;" "<#22E0>")
 ("&nsccue;" "<#22E1>")
 ("&nsqsube;" "<#22E2>")
 ("&nsqsupe;" "<#22E3>")
 ("&lnsim;" "<#22E6>")
 ("&gnsim;" "<#22E7>")
 ("&prnsim;" "<#22E8>")
 ("&scnsim;" "<#22E9>")
 ("&nltri;" "<#22EA>")
 ("&nrtri;" "<#22EB>")
 ("&nltrie;" "<#22EC>")
 ("&nrtrie;" "<#22ED>")
 ("&vellip;" "<#22EE>")
 ("&ctdot;" "<#22EF>")
 ("&utdot;" "<#22F0>")
 ("&dtdot;" "<#22F1>")
 ("&disin;" "<#22F2>")
 ("&lceil;" "<#2308>")
 ("&rceil;" "<#2309>")
 ("&lfloor;" "<#230A>")
 ("&rfloor;" "<#230B>")
 ("&lang;" "<#2329>")
 ("&rang;" "<#232A>")
 ("&Alpha;" "<#0391>")
 ("&Beta;" "<#0392>")
 ("&Gamma;" "<#0393>")
 ("&Delta;" "<#0394>")
 ("&Epsilon;" "<#0395>")
 ("&Zeta;" "<#0396>")
 ("&Eta;" "<#0397>")
 ("&Theta;" "<#0398>")
 ("&Iota;" "<#0399>")
 ("&Kappa;" "<#039A>")
 ("&Lambda;" "<#039B>")
 ("&Mu;" "<#039C>")
 ("&Nu;" "<#039D>")
 ("&Xi;" "<#039E>")
 ("&Omicron;" "<#039F>")
 ("&Pi;" "<#03A0>")
 ("&Rho;" "<#03A1>")
 ("&Sigma;" "<#03A3>")
 ("&Tau;" "<#03A4>")
 ("&Upsilon;" "<#03A5>")
 ("&Phi;" "<#03A6>")
 ("&Chi;" "<#03A7>")
 ("&Psi;" "<#03A8>")
 ("&Omega;" "<#03A9>")
 ("&alpha;" "<#03B1>")
 ("&beta;" "<#03B2>")
 ("&gamma;" "<#03B3>")
 ("&delta;" "<#03B4>")
 ("&epsilon;" "<#03B5>")
 ("&zeta;" "<#03B6>")
 ("&eta;" "<#03B7>")
 ("&theta;" "<#03B8>")
 ("&iota;" "<#03B9>")
 ("&kappa;" "<#03BA>")
 ("&lambda;" "<#03BB>")
 ("&mu;" "<#03BC>")
 ("&nu;" "<#03BD>")
 ("&xi;" "<#03BE>")
 ("&omicron;" "<#03BF>")
 ("&rho;" "<#03C1>")
 ("&sigmaf;" "<#03C2>")
 ("&sigma;" "<#03C3>")
 ("&tau;" "<#03C4>")
 ("&upsilon;" "<#03C5>")
 ("&phi;" "<#03C6>")
 ("&chi;" "<#03C7>")
 ("&psi;" "<#03C8>")
 ("&omega;" "<#03C9>")
 ("&thetasym;" "<#03D1>")
 ("&upsih;" "<#03D2>")
 ("&piv;" "<#03D6>")
 ("&olarr;" "<#21BA>")
 ("&orarr;" "<#21BB>")
 ("&lharu;" "<#21BC>")
 ("&lhard;" "<#21BD>")
 ("&uharr;" "<#21BE>")
 ("&uharl;" "<#21BF>")
 ("&rharu;" "<#21C0>")
 ("&rhard;" "<#21C1>")
 ("&dharr;" "<#21C2>")
 ("&dharl;" "<#21C3>")
 ("&rlarr;" "<#21C4>")
 ("&udarr;" "<#21C5>")
 ("&lrarr;" "<#21C6>")
 ("&llarr;" "<#21C7>")
 ("&uuarr;" "<#21C8>")
 ("&rrarr;" "<#21C9>")
 ("&ddarr;" "<#21CA>")
 ("&lrhar;" "<#21CB>")
 ("&rlhar;" "<#21CC>")
 ("&lArr;" "<#21D0>")
 ("&uArr;" "<#21D1>")
 ("&rArr;" "<#21D2>")
 ("&dArr;" "<#21D3>")
 ("&hArr;" "<#21D4>")
 ("&vArr;" "<#21D5>")
 ("&nwArr;" "<#21D6>")
 ("&neArr;" "<#21D7>")
 ("&seArr;" "<#21D8>")
 ("&swArr;" "<#21D9>")
 ("&lAarr;" "<#21DA>")
 ("&rAarr;" "<#21DB>")
 ("&ziglarr;" "<#21DC>")
 ("&zigrarr;" "<#21DD>")
 ("&larrb;" "<#21E4>")
 ("&rarrb;" "<#21E5>")
 ("&duarr;" "<#21F5>")
 ("&xlarr;" "<#27F5>")
 ("&xrarr;" "<#27F6>")
 ("&xharr;" "<#27F7>")
 ("&xlArr;" "<#27F8>")
 ("&xrArr;" "<#27F9>")
 ("&xhArr;" "<#27FA>")
 ("&dzigrarr;" "<#27FF>")
 ("&xmap;" "<#27FC>")
 ("&lurdshar;" "<#294A>")
 ("&ldrushar;" "<#294B>")
 ("&RightUpDownVector;" "<#294F>")
 ("&DownLeftRightVector;" "<#2950>")
 ("&LeftUpDownVector;" "<#2951>")
 ("&udhar;" "<#296E>")
 ("&duhar;" "<#296F>")
 ("&eth;" "<#00F0>")
 ("&thorn;" "<#00FE>")
 ("&Dstrok;" "<#0110>")
 ("&dstrok;" "<#0111>")
 ("&Hstrok;" "<#0126>")
 ("&hstrok;" "<#0127>")
 ("&imath;" "<#0131>")
 ("&kgreen;" "<#0138>")
 ("&Lstrok;" "<#0141>")
 ("&lstrok;" "<#0142>")
 ("&ENG;" "<#014A>")
 ("&eng;" "<#014B>")
 ("&Tstrok;" "<#0166>")
 ("&tstrok;" "<#0167>")
 ("&DownBreve;" "<#0311>")
 ("&female;" "<#02640>")
 ("&male;" "<#02642>")
 ("&Longleftrightarrow;" "<#027FA>")
 ("&Implies;" "<#021D2>")
 ("&longrightarrow;" "<#027F6>")
 ("&aleph;" "<#02135>")
 ("&uparrow;" "<#02191>")
 ("&Product;" "<#0220F>")
 ("&exponentiale;" "<mathe>")

) ;logic-table

(logic-table mathml-symbol->tm%
 ("&mldr;" "<cdots>")
 ("&ThinSpace;" (hspace "0.1666667em"))
 ("&MediumSpace;" (hspace "0.2222222em"))
 ("&ThickSpace;" (hspace "0.2777778em"))
 (" " (hspace "1em"))
 (" " (hspace "1en"))
) ;logic-table

(logic-table mathml-above->tm%
 ("<overbrace>" "<wide-overbrace>")
 ("<underbrace>" "<wide-underbrace>")
 ("<sqoverbrace>" "<wide-sqoverbrace>")
 ("<squnderbrace>" "<wide-squnderbrace>")
 ("<poverbrace>" "<wide-poverbrace>")
 ("<punderbrace>" "<wide-punderbrace>")
) ;logic-table

(logic-table mathml-below->tm%
 ("<overbrace>" "<wide-overbrace*>")
 ("<underbrace>" "<wide-underbrace*>")
 ("<sqoverbrace>" "<wide-sqoverbrace*>")
 ("<squnderbrace>" "<wide-squnderbrace*>")
 ("<poverbrace>" "<wide-poverbrace*>")
 ("<punderbrace>" "<wide-punderbrace*>")
) ;logic-table

(logic-table mathml-above-below->tm%
 ("<vect>" "<vect>")
 ("<breve>" "<breve>")
 ("<check>" "<check>")
 ("^" "^")
 ("~" "~")
 ("¯" "<wide-bar>")
 ("<invbreve>" "<invbreve>")
 ("<acute>" "<acute>")
 ("<grave>" "<grave>")
 ("<abovering>" "<abovering>")
 ("<dddot>" "<dddot>")
) ;logic-table



(logic-rules ((mathml-operator->tm% 'x 'y) (tm->mathml-operator% 'y 'x))
 ((mathml-symbol->tm% 'x 'y) (mathml-constant->tm% 'x 'y))
 ((mathml-symbol->tm% 'x 'y) (mathml-operator->tm% 'x 'y))
 ((mathml-below->tm% 'x 'y) (mathml-above-below->tm% 'x 'y))
 ((mathml-above->tm% 'x 'y) (mathml-above-below->tm% 'x 'y))
) ;logic-rules

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Special symbols
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(logic-table tm->mathml-left%
 ("(" "(")
 ("[" "[")
 ("{" "{")
 ("langle" "&LeftAngleBracket;")
 ("lfloor" "&LeftFloor;")
 ("lceil" "&LeftCeiling;")
 ("llbracket" "&LeftDoubleBracket;")
 ("/" "/")
) ;logic-table

(logic-table tmtm-left%
  ;; For HTML entities &lfloor;, &lceil, etc.
  ("<lfloor>" "lfloor")
  ("<lceil>" "lceil")
  ("<langle>" "langle")
) ;logic-table

(logic-table tm->mathml-right%
 (")" ")")
 ("]" "]")
 ("}" "}")
 ("rangle" "&RightAngleBracket;")
 ("rfloor" "&RightFloor;")
 ("rceil" "&RightCeiling;")
 ("rrbracket" "&RightDoubleBracket;")
 ("\\\\" "&Backslash;")
) ;logic-table

(logic-table tmtm-right%
  ;; For HTML entities &rfloor;, &rceil, etc.
  ("<rfloor>" "rfloor")
  ("<rceil>" "rceil")
  ("<rangle>" "rangle")
) ;logic-table

(logic-table tm->mathml-big%
 ("sum" "&Sum;")
 ("prod" "&Product;")
 ("int" "&Integral;")
 ("iint" "&Int;")
 ("iiint" "&iiint;")
 ("oiint" "&Conint;")
 ("oiiint" "&Cconint;")
 ("oint" "&ContourIntegral;")
 ("amalg" "&Coproduct;")
 ("cap" "&Intersection;")
 ("cup" "&Union;")
 ("wedge" "&Wedge;")
 ("vee" "&Vee;")
 ("odot" "&CircleDot;")
 ("oplus" "&CirclePlus;")
 ("otimes" "&CircleTimes;")
 ("sqcap" "&SquareIntersection;")
 ;; FIXME: displayed too small
 ("sqcup" "&SquareUnion;")
 ;; FIXME: displayed too small
 ;; ("curlywedge" "&CurlyWedge;")
 ;; ("curlyvee" "&CurlyVee;")
 ;; ("triangleup" "&TriangleUp;")
 ;; ("triangledown" "&TriangleDown;")
 ;; ("box" "&Box;")
 ("pluscup" "&UnionPlus;")
 ;; ("parallel" "&Parallel;")
 ;; ("interleave" "&Interleave;")
) ;logic-table

(logic-table tmtm-big%
  ;; For HTML entities &sum;, &prod;, etc.
  ("<sum>" "sum")
  ("<prod>" "prod")
  ("<int>" "int")
) ;logic-table

(logic-table tm->mathml-above-below%
 ("^" "&Hat;")
 ("~" "&Tilde;")
 ("<bar>" "&OverBar;")
 ("<vect>" "&RightVector;")
 ("<check>" "&Hacek;")
 ("<breve>" "&Breve;")
 ("<invbreve>" "&#x311;")
 ("<acute>" "&DiacriticalAcute;")
 ("<grave>" "&DiacriticalGrave;")
 ("<dot>" "&DiacriticalDot;")
 ("<ddot>" "&DoubleDot;")
 ;;  ("<abovering>" "&AboveRing;")
 ("<wide-varrightarrow>" "&RightArrow;")
 ("<wide-varleftarrow>" "&LeftArrow;")
) ;logic-table

(logic-table tm->mathml-only-above%
 ("<wide-overbrace>" "&OverBrace;")
 ("<wide-underbrace*>" "&UnderBrace;")
 ("<wide-poverbrace>" "&OverParenthesis;")
 ("<wide-punderbrace*>" "&UnderParenthesis;")
 ("<wide-sqoverbrace>" "&OverBracket;")
 ("<wide-squnderbrace*>" "&UnderBracket;")
) ;logic-table

(logic-table tm->mathml-only-below%
 ("<wide-overbrace*>" "&OverBrace;")
 ("<wide-underbrace>" "&UnderBrace;")
 ("<wide-poverbrace*>" "&OverParenthesis;")
 ("<wide-punderbrace>" "&UnderParenthesis;")
 ("<wide-sqoverbrace*>" "&OverBracket;")
 ("<wide-squnderbrace>" "&UnderBracket;")
) ;logic-table

(logic-rules ((tm->mathml-large% 'x 'y) (tm->mathml-left% 'x 'y))
 ((tm->mathml-large% 'x 'y) (tm->mathml-right% 'x 'y))
 ((mathml-left->tm% 'x 'y) (tm->mathml-left% 'y 'x))
 ((mathml-right->tm% 'x 'y) (tm->mathml-right% 'y 'x))
 ((mathml-large->tm% 'x 'y) (mathml-left->tm% 'x 'y))
 ((mathml-large->tm% 'x 'y) (mathml-right->tm% 'x 'y))
 ((mathml-big->tm% 'x 'y) (tm->mathml-big% 'y 'x))
 ((tm->mathml-above% 'x 'y) (tm->mathml-only-above% 'x 'y))
 ((tm->mathml-above% 'x 'y) (tm->mathml-above-below% 'x 'y))
 ((tm->mathml-below% 'x 'y) (tm->mathml-only-below% 'x 'y))
 ((tm->mathml-below% 'x 'y) (tm->mathml-above-below% 'x 'y))
 ((tm->mathml-wide*% 'x 'y) (tm->mathml-only-below% 'x 'y))
 ((tm->mathml-wide*% 'x 'y) (tm->mathml-only-above% 'x 'y))
 ((tm->mathml-wide*% 'x 'y) (tm->mathml-above-below% 'x 'y))
 ((tm->mathml-wide% 'x 'y) (tm->mathml-wide*% 'x 'y))
 ((tm->mathml-wide% "<wide-bar>" "&OverBar;"))
 ((mathml-above->tm% 'x 'y) (tm->mathml-above% 'y 'x))
 ((mathml-below->tm% 'x 'y) (tm->mathml-below% 'y 'x))
 ((mathml-wide->tm% 'x 'y) (tm->mathml-wide*% 'y 'x))
) ;logic-rules
