
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; make-apidoc-module.scm   (derived from build-glue.scm)
;; DESCRIPTION : generates the (texmacs-module (prog glue-symbols))
;;               which provides the scheme API symbols defined in glue
;;               for autocompletion, apidoc...
;; COPYRIGHT   : (C) 2016 the TeXmacs team
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define glue-defs '("build-glue-basic.scm" "build-glue-server.scm"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Convenient output routine
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(define output-sub
  (lambda (l) (if (not (null? l)) (begin (display (car l)) (output-sub (cdr l)))))
) ;define

(define output (lambda l (output-sub l)))


(define (output-copyright from)
  noop
) ;define


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Main build routines
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (build-routine l)
  ;; what exactly do we want to document?
  (let ((name (car l)) (croutine (cadr l)) (ret-type (caaddr l)) (arg-type (cdaddr l)))
    ;;    (output "(" name " " croutine " " ret-type "  " arg-type ")\n")))
    ;; (output l "\n")) ;; everything
    (output "\"" name "\"\n")
  ) ;let
) ;define

(define build-routines
  (lambda (l)
    (if (not (null? l)) (begin (build-routine (car l)) (build-routines (cdr l))))
  ) ;lambda
) ;define


(define (build-main l)
  (build-routines (cddr l))
) ;define

(define-macro build (lambda l (build-main l)))


(begin
  (output "\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n;;\n;; MODULE      : glue-symbols.scm\n;; DESCRIPTION : lists scheme symbols defined in glue \n;;               (for use in autocompletion & apidoc)\n;; COPYRIGHT   : (C) 2016 the TeXmacs team\n;;\n;; This software falls under the GNU general public license version 3 or later.\n;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE\n;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.\n;;\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n;; \n;;        YOU SHOULD DO NOT EDIT THIS FILE\n;;\n;; This file was generated automatically by\n;; /src/src/Scheme/Glue/build-glue/make-apidoc-module.scm\n;; from the glue functions defined in\n;; /src/src/Scheme/Glue/build-glue/build-glue-(basic|server|editor).scm\n;;\n;; It is updated automatically when running the script \n;; /src/src/Scheme/Glue/build-glue\n;;\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;\n\n"
  ) ;output
  (output "(texmacs-module (prog glue-symbols))\n\n")
  (output "(tm-define (all-glued-symbols) '( \n")
  (map load glue-defs)
  (output "))\n")
) ;begin
