;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : chat-model-test.scm
;; DESCRIPTION : Test suite for chat model
;; COPYRIGHT   : (C) 2026  Mogan Contributors
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (generic chat-model-test)
  (:use (generic chat-model)))

(import (liii check))

(check-set-mode! 'report-failed)

(define (test-chat-session-initial-state)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (check (chat-session-id session) => "session-1")
    (check (chat-session-json-path session) => "/tmp/chat.json")
    (check (chat-session-created-at session) => 100)
    (check (chat-session-updated-at session) => 100)
    (check (chat-session-dirty? session) => #f)
    (check (chat-session-block-count session) => 0)
    (check (chat-session-current-block-id session) => #f)))

(define (test-chat-open-block)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'user 101)
    (check (chat-session-block-count session) => 1)
    (check (chat-session-current-block-id session) => "block-1")
    (check (chat-session-dirty? session) => #t)
    (let ((block (chat-session-current-block session)))
      (check (chat-block-id block) => "block-1")
      (check (chat-block-actor block) => 'user)
      (check (chat-block-sealed? block) => #f)
      (check (chat-block-item-count block) => 0)
      (check (chat-block-close-reason block) => #f)
      (check (chat-block-started-at block) => 101)
      (check (chat-block-ended-at block) => #f))))

(define (test-chat-open-second-block-fails)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'user 101)
    (check
      (catch #t
        (lambda ()
          (chat-session-open-block! session "block-2" 'agent 102)
          #f)
        (lambda args #t))
      => #t)
    (check (chat-session-block-count session) => 1)
    (check (chat-session-current-block-id session) => "block-1")
    (let ((block (chat-session-current-block session)))
      (check (chat-block-id block) => "block-1")
      (check (chat-block-sealed? block) => #f)
      (check (chat-block-item-count block) => 0))))

(define (test-chat-append-mergeable-item)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'agent 101)
    (chat-session-append-item! session "item-1" 'text "Hello" #f 102 'streaming)
    (chat-session-append-item! session "item-2" 'text " world" #f 103 'done)
    (let* ((block (chat-session-current-block session))
           (item (chat-block-last-item block)))
      (check (chat-session-current-block-id session) => "block-1")
      (check (chat-session-updated-at session) => 103)
      (check (chat-block-item-count block) => 1)
      (check (chat-block-sealed? block) => #f)
      (check (chat-item-id item) => "item-1")
      (check (chat-item-type item) => 'text)
      (check (chat-item-content item) => "Hello world")
      (check (chat-item-payload item) => #f)
      (check (chat-item-status item) => 'done)
      (check (chat-item-timestamp item) => 103))))

(define (test-chat-append-nonmergeable-item)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'agent 101)
    (chat-session-append-item! session "item-1" 'text "Hello" #f 102 'done)
    (chat-session-append-item! session "item-2" 'tool-call #f
                               `(("title" . "Explored"))
                               103 'done)
    (let ((block (chat-session-current-block session)))
      (check (chat-block-item-count block) => 2)
      (check (chat-item-type (chat-block-item-ref block 0)) => 'text)
      (check (chat-item-type (chat-block-item-ref block 1)) => 'tool-call)
      (check (chat-item-payload (chat-block-item-ref block 1))
             => `(("title" . "Explored"))))))

(define (test-chat-seal-block)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'agent 101)
    (chat-session-append-item! session "item-1" 'text "Hello" #f 102 'done)
    (chat-session-seal-current-block! session 'agent-finished 103)
    (let ((block (chat-session-block-ref session 0)))
      (check (chat-session-current-block-id session) => #f)
      (check (chat-session-updated-at session) => 103)
      (check (chat-block-sealed? block) => #t)
      (check (chat-block-close-reason block) => 'agent-finished)
      (check (chat-block-ended-at block) => 103))))

(define (test-chat-append-after-seal-fails)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'agent 101)
    (chat-session-seal-current-block! session 'agent-stopped 103)
    (check
      (catch #t
        (lambda ()
          (chat-session-append-item! session "item-1" 'text "Hello" #f 104 'done)
          #f)
        (lambda args #t))
      => #t)
    (check (chat-session-current-block-id session) => #f)
    (check (chat-session-block-count session) => 1)
    (let ((block (chat-session-block-ref session 0)))
      (check (chat-block-sealed? block) => #t)
      (check (chat-block-close-reason block) => 'agent-stopped)
      (check (chat-block-item-count block) => 0))))

(define (test-chat-different-mergeable-types-split)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'agent 101)
    (chat-session-append-item! session "item-1" 'text "Hello" #f 102 'done)
    (chat-session-append-item! session "item-2" 'thinking "..." #f 103 'done)
    (let ((block (chat-session-current-block session)))
      (check (chat-block-item-count block) => 2)
      (check (chat-item-type (chat-block-item-ref block 0)) => 'text)
      (check (chat-item-type (chat-block-item-ref block 1)) => 'thinking))))

(define (test-chat-json-export)
  (let ((session (make-chat-session "session-1" "/tmp/chat.json" 100)))
    (chat-session-open-block! session "block-1" 'user 101)
    (chat-session-append-item! session "item-1" 'text "Hello" #f 102 'done)
    (chat-session-seal-current-block! session 'user-submitted 103)
    (let* ((json (chat-session->json session))
           (meta (assoc-ref json "meta"))
           (blocks (assoc-ref json "blocks"))
           (block (vector-ref blocks 0))
           (items (assoc-ref block "items"))
           (item (vector-ref items 0)))
      (check (assoc-ref json "id") => "session-1")
      (check (assoc-ref meta "version") => 1)
      (check (assoc-ref meta "current_block_id") => #f)
      (check (assoc-ref meta "dirty") => #t)
      (check (vector-length blocks) => 1)
      (check (assoc-ref block "actor") => "user")
      (check (assoc-ref block "sealed") => #t)
      (check (assoc-ref block "close_reason") => "user-submitted")
      (check (vector-length items) => 1)
      (check (assoc-ref item "type") => "text")
      (check (assoc-ref item "status") => "done")
      (check (assoc-ref item "timestamp") => 102)
      (check (assoc-ref item "payload") => #f)
      (check (assoc-ref item "content") => "Hello"))))

(tm-define (regtest-chat-model)
  (test-chat-session-initial-state)
  (test-chat-open-block)
  (test-chat-open-second-block-fails)
  (test-chat-append-mergeable-item)
  (test-chat-append-nonmergeable-item)
  (test-chat-seal-block)
  (test-chat-append-after-seal-fails)
  (test-chat-different-mergeable-types-split)
  (test-chat-json-export)
  (check-report))

(tm-define (test_chat-model-test)
  (regtest-chat-model))
