name: CI for moebius on Windows

on:
  push:
    branches: [ main ]
    paths:
      - 'moebius/Data/**'
      - 'moebius/Kernel/**'
      - 'moebius/Scheme/**'
      - 'moebius/moebius/**'
      - 'moebius/tests/**'
      - 'moebius/xmake.lua'
      - '.github/workflows/ci-moebius-windows.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'moebius/Data/**'
      - 'moebius/Kernel/**'
      - 'moebius/Scheme/**'
      - 'moebius/moebius/**'
      - 'moebius/tests/**'
      - 'moebius/xmake.lua'
      - '.github/workflows/ci-moebius-windows.yml'
  workflow_dispatch:

env:
  XMAKE_GLOBALDIR: "${{ github.workspace }}\\.xmake-global"

jobs:
  windowsbuild:
    runs-on: windows-2025
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v3.0.4
      - name: update repo
        run: xrepo update-repo
      - name: git crlf
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: qt683-${{ runner.os }}-${{ runner.arch }}-xrepo-${{ hashFiles('xmake/vars.lua', 'moebius/xmake.lua') }}
      - name: cache xmake
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('xmake/vars.lua', 'moebius/xmake.lua') }}
      - name: config
        run: xmake config --policies=build.ccache --yes -vD -m releasedbg --plat=windows
      - name: build
        run: xmake build --yes -vD libmoebius
      - name: test
        run: xmake test "moebius_tests/*"
