name: Lint moebius

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'moebius/Data/**'
      - 'moebius/Kernel/**'
      - 'moebius/tests/**'
      - 'moebius/bench/**'
      - 'moebius/xmake.lua'
      - '.github/workflows/ci-moebius-format-linter.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: 'moebius'
        exclude: 'moebius/build moebius/xmake moebius/workflow moebius/github'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16
        style: file
